# Generated by Django 5.0.6 on 2024-07-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=50)),
                ('charname', models.CharField(blank=True, max_length=200)),
                ('birthname', models.CharField(blank=True, max_length=200)),
                ('types', models.CharField(blank=True, max_length=200)),
                ('universes', models.CharField(blank=True, max_length=200)),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('superpowers', models.CharField(blank=True, max_length=200)),
                ('religions', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('memberof', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
