# Generated by Django 5.0.6 on 2024-07-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterprofile',
            name='birthplace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='gender',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='memberof',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='occupation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='religions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='superpowers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='universes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
