# Generated by Django 5.0.6 on 2024-07-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_characters', '0002_alter_characterprofile_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterprofile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='char',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='religions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
